# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_windows
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_windows)
  Schizle_config = debug_windows
endif
ifeq ($(config),debug_mac)
  Schizle_config = debug_mac
endif
ifeq ($(config),debug_linux)
  Schizle_config = debug_linux
endif
ifeq ($(config),release_windows)
  Schizle_config = release_windows
endif
ifeq ($(config),release_mac)
  Schizle_config = release_mac
endif
ifeq ($(config),release_linux)
  Schizle_config = release_linux
endif

PROJECTS := Schizle

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Schizle:
ifneq (,$(Schizle_config))
	@echo "==== Building Schizle ($(Schizle_config)) ===="
	@${MAKE} --no-print-directory -C . -f Schizle.make config=$(Schizle_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Schizle.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_windows"
	@echo "  debug_mac"
	@echo "  debug_linux"
	@echo "  release_windows"
	@echo "  release_mac"
	@echo "  release_linux"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Schizle"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"