# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Schizle_config = debug
endif
ifeq ($(config),release)
  Schizle_config = release
endif

PROJECTS := Schizle

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Schizle:
ifneq (,$(Schizle_config))
	@echo "==== Building Schizle ($(Schizle_config)) ===="
	@${MAKE} --no-print-directory -C . -f Schizle.make config=$(Schizle_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Schizle.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Schizle"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"